name: "Show permissions bug"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: node:lts
      options: --user 1001

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Build Frontend Assets
        run: npm run production
