name: "Show permissions bug"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: node:lts

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Test
        run: touch public/mix-manifest.json
      - name: Test
        run: chmod 777 public/mix-manifest.json
      - name: Build Frontend Assets
        run: npm run production
