name: "Show permissions bug"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout: 30
    container:
      image: node:lts

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Build Frontend Assets
        run: npm run production
